print('=========================')
print('|      Hello World      |')
print('=========================')
# print('I like typing this.')
# print('This is fun.')
# print('Yay! Printing.')
# print("I'd much rather you 'not'.")
# print('I "said" do not touch this.')
print("I'm the only one here?")